name: Test and Coverage Check

on:
  #pull_request:
  push:
    paths:
      - '**/*.js'

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Generate Code Coverage
        run: npm run coverage

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4.3.0
        with:
          name: coverage-report
          path: coverage
