name: Check Code Patterns

on:
  push:
    branches:
      - '**' # Run on all branches

jobs:
  check-patterns:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Get changed files
        id: abc
        uses: jitterbit/get-changed-files@v1
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Printing
        run: |
          echo "All:"
          echo "${{ steps.abc.outputs.all }}"
          echo "Added:"
          echo "${{ steps.abc.outputs.added }}"
          echo "Removed:"
          echo "${{ steps.abc.outputs.removed }}"
          echo "Renamed:"
          echo "${{ steps.abc.outputs.renamed }}"
          echo "Modified:"
          echo "${{ steps.abc.outputs.modified }}"
          echo "Added+Modified:"
          echo "${{ steps.abc.outputs.added_modified }}"
    
      - name: Check for forbidden patterns
        run: |
          forbidden_pattern="Thread\.ofVirtual\(\)|Thread\.newVirtualThread\(\)"

          # Check for patterns in all modified files
          if grep -E "$forbidden_pattern" ${{ steps.abc.outputs.modified }}; then
            echo "Error: Your changes include forbidden patterns: Thread.ofVirtual(), Thread.newVirtualThread()"
            exit 1
          fi
   

    # - name: Check for forbidden patterns
    #   run: |
    #     forbidden_pattern="Thread\.ofVirtual\(\)"
    #     git diff --name-only ${{ github.base_ref }}..${{ github.sha }}

    #     if git diff --name-only ${{ github.base_ref }}..${{ github.sha }} | grep -E "$forbidden_pattern" >/dev/null; then
    #       echo "Error: Your changes include forbidden patterns: Thread.ofVirtual(), Thread.newVirtualThread()"
    #       exit 1
    #     fi

    
