name: Check Code Patterns

on:
  pull_request:
    
jobs:
  check-patterns:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for forbidden patterns
      run: |
        forbidden_pattern="Thread\.ofVirtual\(\)|Thread\.newVirtualThread\(\)"

        if git diff --name-only ${{ github.base_ref }}..${{ github.sha }} | grep -E "$forbidden_pattern" >/dev/null; then
          echo "Error: Your changes include forbidden patterns: Thread.ofVirtual(), Thread.newVirtualThread()"
          exit 1
        fi
