name: List Staged Files

on:
  push:
    branches:
      - main # Adjust the branch as needed

jobs:
  list-staged-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Staged Files
        run: |
          staged_files=$(git diff --name-only --cached)
          if [ -n "$staged_files" ]; then
            echo "Staged Files:"
            echo "$staged_files"
          else
            echo "No files staged."
          fi